# Generated by Django 5.2.7 on 2025-10-22 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessment.question')),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='assessment.businesstype')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('output_type', models.CharField(default='Result', max_length=100)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=50)),
                ('recommended_services', models.TextField(blank=True, help_text='Example: AML Screening, eKYC, Transaction Monitoring')),
                ('sanctions_list_activation', models.TextField(blank=True, help_text='Example: UNSC, OFAC, EU, SAMA')),
                ('monitoring_frequency', models.CharField(blank=True, help_text='Example: Real-Time or Periodic', max_length=100)),
                ('tags', models.TextField(blank=True, help_text='Example: High Risk, Geo-Flagged, Manual Review')),
                ('activated_scenarios', models.TextField(blank=True, help_text='List of activated rules or scenarios')),
                ('output_summary', models.TextField(blank=True, help_text='Final summary or explanation of the result')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessment.businesstype')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessment.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.section'),
        ),
    ]
