# Generated by Django 5.2.7 on 2025-10-23 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='scenario',
        ),
        migrations.AddField(
            model_name='section',
            name='business_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessment.businesstype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Scenario',
        ),
    ]
