# Generated by Django 5.2.7 on 2025-10-22 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_question_scenario_choice_question_scenario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='scenario',
            name='category',
        ),
        migrations.CreateModel(
            name='ScenarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(max_length=50)),
                ('recommended_services', models.TextField()),
                ('sanctions_activation', models.TextField()),
                ('monitoring_frequency', models.CharField(max_length=50)),
                ('tags', models.TextField()),
                ('output_summary', models.TextField()),
                ('scenario_description', models.TextField(blank=True)),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessment.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('business', 'Business Profile'), ('compliance', 'Compliance Stack'), ('risk', 'Risk Evaluation')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessment.scenario')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.section'),
            preserve_default=False,
        ),
    ]
