# Generated by Django 5.2.7 on 2025-10-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_remove_section_scenario_section_business_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتيب القسم (1، 2، 3...)'),
        ),
    ]
