# Generated by Django 5.2.7 on 2025-10-25 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='العملية')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستخدم')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل إضافية')),
            ],
            options={
                'verbose_name': 'سجل لوحة التحكم',
                'verbose_name_plural': 'سجلات لوحة التحكم',
                'ordering': ['-created_at'],
            },
        ),
    ]
